#!/usr/bin/env python3
"""Regenerate the bundled BIC6 prefix list from the GLEIF BIC-to-LEI mapping.

    python3 scripts/refresh_bic_registry.py            # latest published file
    python3 scripts/refresh_bic_registry.py FILE.csv   # a downloaded CSV

Writes the same list to both SDKs, and the licence notice to both packages:

    euredact-python/src/euredact/rules/bic_gleif.py
    euredact-ts/src/rules/bicGleif.ts
    euredact-python/NOTICE, euredact-ts/NOTICE

The mapping is published monthly by GLEIF and developed by SWIFT. Its licence
(the BIC/LEI Mapping Table License Agreement) allows redistribution for any
purpose provided every copy, in whole or in part, carries SWIFT's notice dated
with the version used. The generated files carry it, and this script writes the
date from the file it read, so a refresh cannot leave a stale notice behind.

Only the BIC6 prefix (institution + country) is kept, for the countries the
engine supports: the prefix is the stable part of a BIC, branch codes churn.
Stdlib only.
"""

from __future__ import annotations

import csv
import io
import json
import re
import sys
import textwrap
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PY_OUT = ROOT / "euredact-python" / "src" / "euredact" / "rules" / "bic_gleif.py"
TS_OUT = ROOT / "euredact-ts" / "src" / "rules" / "bicGleif.ts"
LATEST = "https://mapping.gleif.org/api/v2/bic-lei/latest"

#: The engine's 31 countries, as BIC country codes: Greece is GR (EL in the
#: engine) and the United Kingdom GB (UK in the engine).
COUNTRIES = (
    "AT", "BE", "BG", "CH", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FR",
    "GB", "GR", "HR", "HU", "IE", "IS", "IT", "LT", "LU", "LV", "MT", "NL",
    "NO", "PL", "PT", "RO", "SE", "SI", "SK",
)

MONTHS = ("January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December")


def notice(version: str) -> str:
    """SWIFT's required notice, verbatim, dated with the mapping version."""
    return (
        f"SWIFT © and database rights {version}. All rights reserved.\n"
        "This Mapping Table has been developed by SWIFT. Any use of the Mapping "
        "Table, in whole or in part, is subject to the BIC/LEI Mapping Table "
        "License Agreement as published with the Mapping Table available on "
        "GLEIF's website.\n"
        "The Mapping Table is updated monthly. For the latest BIC information "
        "and updates, always refer to www.swift.com/bic ."
    )


def _download() -> tuple[str, bytes]:
    with urllib.request.urlopen(LATEST, timeout=60) as resp:
        meta = json.load(resp)["data"]["attributes"]
    with urllib.request.urlopen(meta["downloadLink"].replace("\\/", "/"), timeout=120) as resp:
        archive = zipfile.ZipFile(io.BytesIO(resp.read()))
    name = next(n for n in archive.namelist() if n.lower().endswith(".csv"))
    return name, archive.read(name)


def _version(file_name: str) -> str:
    found = re.search(r"(20\d\d)(\d\d)\d\d", file_name)
    if not found:
        sys.exit(f"cannot read a version date from {file_name!r}")
    return f"{MONTHS[int(found[2]) - 1]} {found[1]}"


def prefixes(csv_bytes: bytes) -> dict[str, list[str]]:
    """Institution codes per country, from the BIC column."""
    wanted = set(COUNTRIES)
    by_country: dict[str, set[str]] = {c: set() for c in COUNTRIES}
    for row in csv.DictReader(io.StringIO(csv_bytes.decode("utf-8-sig"))):
        bic = (row.get("BIC") or "").strip().upper()
        if len(bic) in (8, 11) and bic[:6].isalpha() and bic[4:6] in wanted:
            by_country[bic[4:6]].add(bic[:4])
    return {c: sorted(codes) for c, codes in by_country.items()}


def packed(by_country: dict[str, list[str]]) -> list[str]:
    """One line per country: "DE AARB COMM ...", institution codes sorted."""
    return [f"{c} {' '.join(codes)}" for c, codes in sorted(by_country.items()) if codes]


def _py_literal(text: str, indent: int, width: int = 88) -> str:
    """*text* as implicitly concatenated string literals, each line in *width*."""
    room = width - indent - 4
    chunks, current = [], ""
    for piece in re.split(r"(?<= )", text):
        if current and len(repr(current + piece)) > room:
            chunks.append(current)
            current = ""
        current += piece
    chunks.append(current)
    return "".join(" " * indent + repr(chunk) + "\n" for chunk in chunks)


def write(version: str, source: str, by_country: dict[str, list[str]]) -> int:
    lines = packed(by_country)
    total = sum(len(v) for v in by_country.values())
    text = notice(version)
    header = (
        "Generated by scripts/refresh_bic_registry.py from the GLEIF BIC-to-LEI "
        f"mapping ({source}); do not edit by hand. {total:,} BIC6 prefixes for "
        "the engine's 31 countries."
    )
    py_notice = "\n".join(
        "# " + wrapped if wrapped else "#"
        for line in (text + "\n\n" + header).splitlines()
        for wrapped in (textwrap.wrap(line, 86) or [""])
    )
    PY_OUT.write_text(
        f"{py_notice}\n"
        '"""BIC6 prefixes from the GLEIF BIC-to-LEI mapping (see the notice above)."""\n\n'
        "from __future__ import annotations\n\n"
        f"VERSION = {version!r}\n\n"
        "NOTICE = (\n" + _py_literal(text, 4) + ")\n\n"
        "#: One line per country: the country code, then its institution codes.\n"
        "PACKED = (\n" + "".join(_py_literal(line + "\n", 4) for line in lines) + ")\n\n\n"
        "def bic6_prefixes() -> frozenset[str]:\n"
        '    """Every bundled prefix, as institution code + country code."""\n'
        "    out: set[str] = set()\n"
        "    for line in PACKED.splitlines():\n"
        "        country, *codes = line.split()\n"
        "        out.update(code + country for code in codes)\n"
        "    return frozenset(out)\n",
        encoding="utf-8",
    )
    ts_notice = "\n".join(" * " + line if line else " *" for line in (text + "\n\n" + header).splitlines())
    TS_OUT.write_text(
        f"/*\n{ts_notice}\n */\n\n"
        f"export const VERSION = {json.dumps(version)};\n\n"
        f"export const NOTICE = {json.dumps(text, ensure_ascii=False)};\n\n"
        "/** One line per country: the country code, then its institution codes. */\n"
        "const PACKED = [\n" + "".join(f"  {json.dumps(line)},\n" for line in lines) + "];\n\n"
        "/** Every bundled prefix, as institution code + country code. */\n"
        "export function bic6Prefixes(): Set<string> {\n"
        "  const out = new Set<string>();\n"
        "  for (const line of PACKED) {\n"
        '    const [country, ...codes] = line.split(" ");\n'
        "    for (const code of codes) out.add(code + country);\n"
        "  }\n"
        "  return out;\n"
        "}\n",
        encoding="utf-8",
    )
    for package in (ROOT / "euredact-python", ROOT / "euredact-ts"):
        (package / "NOTICE").write_text(
            "euredact\n"
            "Copyright the euredact authors. Licensed under the Apache License 2.0;\n"
            "see LICENSE.\n\n"
            "This package bundles BIC6 prefixes derived from the BIC/LEI Mapping Table,\n"
            "published by GLEIF (https://www.gleif.org) and developed by SWIFT, used\n"
            "under the BIC/LEI Mapping Table License Agreement:\n\n"
            + text + "\n",
            encoding="utf-8",
        )
    return total


def main() -> int:
    if len(sys.argv) > 1:
        path = Path(sys.argv[1])
        name, data = path.name, path.read_bytes()
    else:
        name, data = _download()
    version = _version(name)
    total = write(version, name, prefixes(data))
    print(f"{total:,} prefixes from {name} ({version}) -> {PY_OUT.relative_to(ROOT)}, {TS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
